###
POST http://localhost:3000/messages/send/6575fc5fd5874d448b4ca1fa
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2FicmllbCIsImNvbnRhY3QiOiJnYWJAbWFpbC5jb20iLCJpYXQiOjE3MDIyMzEzNTMsImV4cCI6MTcwNDgyMzM1Mywic3ViIjoiNjU3NWZjNGZkNTg3NGQ0NDhiNGNhMWY4In0.uTpAyzWomo4i9-zsDax6wF4TsUEPZ7xX6TzQCIDYOj0

{
	"content": "Hello, buddy"
}

###
GET http://localhost:3000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2FicmllbCIsImNvbnRhY3QiOiJnYWJAbWFpbC5jb20iLCJpYXQiOjE3MDIwNzgwNDQsImV4cCI6MTcwNDY3MDA0NCwic3ViIjoiNjU3MjMwODZkMDk5MzYwNTg2MWEwMjFkIn0.jjpg27m06Mn3riPO1rWWBDPJdX8lOnvFT7nH5zSUf_c

###
DELETE  http://localhost:3000/messages/6574847973182786a0981657
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2FicmllbCIsImNvbnRhY3QiOiJnYWJAbWFpbC5jb20iLCJpYXQiOjE3MDIwNzgwNDQsImV4cCI6MTcwNDY3MDA0NCwic3ViIjoiNjU3MjMwODZkMDk5MzYwNTg2MWEwMjFkIn0.jjpg27m06Mn3riPO1rWWBDPJdX8lOnvFT7nH5zSUf_c


###
DELETE  http://localhost:3000/messages/reset/database
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2FicmllbCIsImNvbnRhY3QiOiJnYWJAbWFpbC5jb20iLCJpYXQiOjE3MDIwNzgwNDQsImV4cCI6MTcwNDY3MDA0NCwic3ViIjoiNjU3MjMwODZkMDk5MzYwNTg2MWEwMjFkIn0.jjpg27m06Mn3riPO1rWWBDPJdX8lOnvFT7nH5zSUf_c
